const STORAGE_KEY='trpg-window:state:v2';
const defaults={player:{name:'이름 없음',level:1,title:'모험가',hp:10,maxHp:10,sp:10,maxSp:10},day:1,location:'장소 미정',speakers:[{id:'sample',name:'대화 상대',role:'현재 발화자',asset:'(인물)'}],characters:[],equipment:[],essences:[],inventory:[],records:[],combat:{active:false,enemy:{name:'검은 늑대',level:8,hp:350,maxHp:350,asset:'(몬스터)'}}};
let state=load();const $=s=>document.querySelector(s);
function clone(x){return JSON.parse(JSON.stringify(x))}function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return {...clone(defaults),...raw,player:{...defaults.player,...(raw.player||{})},combat:{...clone(defaults.combat),...(raw.combat||{})}}}catch{return clone(defaults)}}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderSpeakers(){const row=$('#speakerRow'),list=state.speakers||[];row.innerHTML=list.length?list.slice(0,5).map((c,i)=>`<article class="speaker-card ${i===list.length-1?'active':''}"><div class="speaker-asset">${esc(c.asset||`(${c.name})`)}</div><strong>${esc(c.name)}</strong><small>${esc(c.role||'')}</small></article>`).join(''):`<div class="empty-speaker">현재 대화에 참여한 인물이 없습니다.</div>`}
function pct(v,m){return Math.max(0,Math.min(100,(Number(v)||0)/(Number(m)||1)*100))}function render(){const p=state.player;$('#playerName').textContent=p.name;$('#playerMeta').textContent=`Lv. ${p.level} · ${p.title}`;$('#playerAvatar').textContent=(p.name||'?')[0];$('#locationText').textContent=state.location;$('#mapLocation').textContent=state.location;$('#dayText').textContent=`DAY ${state.day||1}`;$('#hpBar').style.width=pct(p.hp,p.maxHp)+'%';$('#spBar').style.width=pct(p.sp,p.maxSp)+'%';$('#hpText').textContent=`${p.hp} / ${p.maxHp}`;$('#spText').textContent=`${p.sp} / ${p.maxSp}`;renderSpeakers();const c=state.combat||{};$('#combatLayer').classList.toggle('hidden',!c.active);$('#mapLayer').classList.toggle('paused',!!c.active);if(c.active){const e=c.enemy||{};$('#enemyName').textContent=e.name||'몬스터';$('#enemyLevel').textContent=`Lv. ${e.level??'?'}`;$('#enemyHpBar').style.width=pct(e.hp,e.maxHp)+'%';$('#enemyHpText').textContent=`HP ${e.hp??'?'} / ${e.maxHp??'?'}`;$('.enemy-asset').textContent=e.asset||'(몬스터)'}}
const labels={people:'인물',equipment:'장비',essence:'정수',inventory:'소지품',map:'지도',record:'기록'};function cards(list,empty){return list?.length?`<div class="drawer-grid">${list.map(x=>`<div class="data-card"><strong>${esc(x.name||x.title||'기록')}</strong><small>${esc(x.description||x.role||'')}</small></div>`).join('')}</div>`:`<div class="data-card"><small>${empty}</small></div>`}function openDrawer(tab){$('#drawerTitle').textContent=labels[tab]||tab;let html='';if(tab==='people')html=cards(state.characters,'등록된 인물이 없습니다.');if(tab==='equipment')html=cards(state.equipment,'장비 데이터가 연결되면 이곳에 표시됩니다.');if(tab==='essence')html=cards(state.essences,'정수 데이터가 연결되면 이곳에 표시됩니다.');if(tab==='inventory')html=cards(state.inventory,'소지품 데이터가 연결되면 이곳에 표시됩니다.');if(tab==='map')html='<div class="data-card"><strong>현재 지도</strong><small>메인 화면의 지도 에셋을 확대해서 보여줄 영역입니다.</small></div>';if(tab==='record')html=cards(state.records,'중요 사건과 기록이 이곳에 쌓입니다.');$('#drawerBody').innerHTML=html;$('#drawer').classList.remove('hidden');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>openDrawer(b.dataset.tab));$('#closeDrawer').onclick=()=>$('#drawer').classList.add('hidden');
$('#editBtn').onclick=()=>{const f=$('#editForm'),p=state.player;f.name.value=p.name;f.level.value=p.level;f.title.value=p.title;f.hp.value=p.hp;f.maxHp.value=p.maxHp;f.sp.value=p.sp;f.maxSp.value=p.maxSp;f.location.value=state.location;f.day.value=state.day;f.combat.checked=!!state.combat.active;$('#editDialog').showModal()};$('#editForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.player={name:f.get('name').trim()||'이름 없음',level:+f.get('level')||1,title:f.get('title').trim()||'모험가',hp:Math.max(0,+f.get('hp')||0),maxHp:Math.max(1,+f.get('maxHp')||1),sp:Math.max(0,+f.get('sp')||0),maxSp:Math.max(1,+f.get('maxSp')||1)};state.location=f.get('location').trim()||'장소 미정';state.day=Math.max(1,+f.get('day')||1);state.combat.active=f.get('combat')==='on';$('#editDialog').close();save()});
window.TRPGWindow={getState:()=>clone(state),setState(next){state={...state,...clone(next)};save()},setSpeakers(speakers){state.speakers=clone(speakers||[]);save()},startCombat(enemy){state.combat={active:true,enemy:{...clone(defaults.combat.enemy),...clone(enemy||{})}};save()},endCombat(){state.combat.active=false;save()},reset(){state=clone(defaults);save()}};render();