const STORAGE_KEY='trpg-window:state:v1';
const defaults={player:{name:'이름 없음',level:1,title:'모험가',hp:10,maxHp:10,sp:10,maxSp:10},location:'장소 미정',characters:[],equipment:[],essences:[]};
let state=load();let activeTab='people';
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
const $=s=>document.querySelector(s);
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function portrait(c,mini=false){if(c.portrait)return `<img class="${mini?'mini-avatar':'portrait-img'}" src="${esc(c.portrait)}" alt="${esc(c.name)}"/>`;return `<div class="${mini?'mini-avatar':'portrait-placeholder'}">${esc((c.name||'?')[0])}</div>`}
function render(){const p=state.player;$('#playerName').textContent=p.name;$('#playerMeta').textContent=`Lv. ${p.level} · ${p.title}`;$('#playerAvatar').textContent=(p.name||'?')[0];$('#locationText').textContent=state.location||'장소 미정';const hp=Math.max(0,Math.min(100,p.hp/p.maxHp*100||0)),sp=Math.max(0,Math.min(100,p.sp/p.maxSp*100||0));$('#hpBar').style.width=hp+'%';$('#spBar').style.width=sp+'%';$('#hpText').textContent=`${p.hp} / ${p.maxHp}`;$('#spText').textContent=`${p.sp} / ${p.maxSp}`;$('#sceneCharacters').innerHTML=state.characters.length?state.characters.slice(0,6).map(c=>`<article class="portrait-card" data-id="${c.id}">${portrait(c)}<strong>${esc(c.name)}</strong><small>${esc(c.role|| (c.party?'동료':'등장인물'))}</small></article>`).join(''):`<div class="empty" style="grid-column:1/-1">아직 장면에 등록된 인물이 없습니다.<br>ChatGPT와 플레이하며 만난 인물을 추가해보세요.</div>`;renderPanel()}
function renderPanel(){const panel=$('#panel');if(activeTab==='people'){panel.innerHTML=state.characters.length?state.characters.map(c=>`<div class="list-card">${portrait(c,true)}<div><strong>${esc(c.name)}${c.party?' · 동료':''}</strong><small>${esc(c.role||'설명 없음')}</small></div></div>`).join(''):`<div class="empty">등록된 인물이 없습니다.</div>`;return}if(activeTab==='equipment'){panel.innerHTML=state.equipment.length?state.equipment.map(x=>`<div class="list-card"><div><strong>${esc(x.name)}</strong><small>${esc(x.description||'')}</small></div></div>`).join(''):`<div class="empty">장비 동기화 영역<br>추후 외부 게임 상태와 연결할 수 있습니다.</div>`;return}if(activeTab==='essence'){panel.innerHTML=state.essences.length?state.essences.map(x=>`<div class="list-card"><div><strong>${esc(x.name)}</strong><small>${esc(x.description||'')}</small></div></div>`).join(''):`<div class="empty">정수 동기화 영역<br>추후 외부 게임 상태와 연결할 수 있습니다.</div>`;return}panel.innerHTML=`<div class="empty">지도 영역<br>게임 세계가 정해지면 지도 데이터를 연결합니다.</div>`}
$('#addCharacterBtn').onclick=()=>$('#characterDialog').showModal();
$('#characterForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.characters.push({id:crypto.randomUUID(),name:f.get('name').trim(),role:f.get('role').trim(),portrait:f.get('portrait').trim(),party:f.get('party')==='on'});e.currentTarget.reset();$('#characterDialog').close();save()});
$('#editBtn').onclick=()=>{const f=$('#editForm'),p=state.player;f.name.value=p.name;f.level.value=p.level;f.title.value=p.title;f.hp.value=p.hp;f.maxHp.value=p.maxHp;f.sp.value=p.sp;f.maxSp.value=p.maxSp;f.location.value=state.location;$('#editDialog').showModal()};
$('#editForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.player={name:f.get('name').trim()||'이름 없음',level:+f.get('level')||1,title:f.get('title').trim()||'모험가',hp:Math.max(0,+f.get('hp')||0),maxHp:Math.max(1,+f.get('maxHp')||1),sp:Math.max(0,+f.get('sp')||0),maxSp:Math.max(1,+f.get('maxSp')||1)};state.location=f.get('location').trim()||'장소 미정';$('#editDialog').close();save()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeTab=b.dataset.tab;renderPanel()});
window.TRPGWindow={getState:()=>structuredClone(state),setState(next){state={...state,...next};save()},reset(){state=structuredClone(defaults);save()}};
render();